export const ICON_TYPES = [
  "Add",
  "AddCircle",
  "ArrowClockwise",
  "ArrowDown",
  "ArrowLeft",
  "ArrowMaximize",
  "ArrowMinimize",
  "ArrowRight",
  "ArrowSort",
  "ArrowTrending",
  "ArrowUp",
  "Backspace",
  "BookOpen",
  "Bookmark",
  "CalendarLtr",
  "CalligraphyPen",
  "CaretDown",
  "CaretLeft",
  "CaretRight",
  "CaretUp",
  "ChatEmpty",
  "Checkmark",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "Clock",
  "Cloud",
  "CloudArrowUp",
  "CloudFlow",
  "Code",
  "CodeBlock",
  "Cube",
  "Delete",
  "Dismiss",
  "DocumentHeart",
  "Edit",
  "ErrorCircle",
  "Eye",
  "EyeOff",
  "Filter",
  "GridDots",
  "Heart",
  "Important",
  "Javascript",
  "Key",
  "Lightbulb",
  "Link",
  "Mic",
  "Money",
  "Navigation",
  "Open",
  "Phone",
  "ProjectionScreen",
  "Search",
  "Settings",
  "SignOut",
  "StackStar",
  "Star",
  "Subtract",
  "TextFont",
  "Wallet",
  "WindowApps",
] as const;

export type IconTypes = typeof ICON_TYPES[number];

export const ICON_COLORS = [
  "white",
  "black-75",
  "mineral-10",
  "mineral-20",
  "mineral-30",
  "mineral-40",
  "mineral-60",
  "mineral-70",
  "mineral-80",
  "mineral-90",
  "teal-40",
  "teal-60",
  "teal-70",
  "purple-40",
  "purple-60",
  "purple-70",
] as const;

export type IconColorTypes = typeof ICON_COLORS[number];

export const TAG_COLORS = [
  "mineral",
  "teal",
  "purple",
  "green",
  "red",
  "yellow",
  "cyan",
  "orange",
  "pink",
] as const;

export type TagTypes = typeof TAG_COLORS[number];
